version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx:23.12.0
    depends_on: [orthanc, orthanc-auth-service]
    restart: unless-stopped
    ports: ["8080:80"]
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_OHIF: "true"
      ENABLE_MEDDREAM: "true"
      ENABLE_ORTHANC_FOR_API: "true"

  orthanc:
    image: osimis/orthanc:master-full
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC_JSON: |
        {
          "Name": "FMCA PACS SYSTEM",
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "UiOptions": {
              "EnableShares": true,
              "DefaultShareDuration": 0,
              "ShareDurations": [0, 7, 15, 30, 90, 365],
              "EnableOpenInOhifViewer3": true,
              "EnableOpenInMedDreamViewer": true,
              "OhifViewer3PublicRoot": "https://techxploit.com.ng/ohif/"
              "MeddreamViewerPublicRoot": https://techxploit.com.ng/meddream/"
            },
            "Tokens" : {
              "InstantLinksValidity": 3600,
              "ShareType": "ohif-viewer-publication"
            },
            "Keycloak" : {
              "Enable": true,
              "Url": "https://techxploit.com.ng/keycloak/",
              "Realm": "orthanc",
              "ClientId": "orthanc"
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "change-me",
            "StandardConfigurations" : [
              "osimis-web-viewer",
              "stone-webviewer",
              "orthanc-explorer-2"
            ],
            "CheckedLevel": "studies"
          },
          "DicomWeb": {
            "Enable": true,
            "PublicRoot": "/orthanc/dicom-web/"
          }
        }
      
    volumes:
      - /data:/var/lib/orthanc/db

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:23.12.0
    depends_on: [keycloak]
    volumes:
      - ./permissions.jsonc:/orthanc_auth_service/permissions.json
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "https://techxploit.com.ng/orthanc/"
      PUBLIC_LANDING_ROOT: "https://techxploit.com.ng/orthanc/ui/app/token-landing.html"
      USERS: |
        {
          "share-user": "change-me"
        }
      MEDDREAM_TOKEN_SERVICE_URL: "http://meddream-token-service:8088/v3/generate"
      PUBLIC_MEDDREAM_ROOT: "https://techxploit.com.ng/meddream/"
      PERMISSIONS_FILE_PATH: "/orthanc_auth_service/permissions.json"

  orthanc-for-api:
    image: osimis/orthanc:master-full
    volumes:
      - /data:/var/lib/orthanc/db
      - ./meddream/meddream-plugin.py:/scripts/meddream-plugin.py
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for API"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/scripts/meddream-plugin.py"
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_MED_DREAM_VIEWER: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__MED_DREAM_VIEWER_PUBLIC_ROOT: "https://techxploit.com.ng/meddream/"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-api/dicom-web/"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC_JSON: |
        {
          "RegisteredUsers": {
            "meddream-user": "change-me",
            "script-user": "change-me",
            "dicom-web-client-user": "change-me"
          }
        }

  keycloak:
    image: orthancteam/orthanc-keycloak:23.12.0
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "https://techxploit.com.ng/keycloak"
      KC_HOSTNAME_ADMIN_URL: "https://techxploit.com.ng/keycloak"
    env_file:
      - ./secrets/KEYCLOAK_ADMIN_PASSWORD.env
  
  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data:Z"] 
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  
  ohif:
    image: orthancteam/ohif-v3:23.12.0
    restart: unless-stopped

  meddream-token-service:
    image: orthancteam/meddream-token-service:23.12.0
    restart: unless-stopped

  meddream-viewer:
    image: orthancteam/meddream-viewer:23.12.0
    restart: unless-stopped
    depends_on:
      - orthanc-for-api
    environment:
      integration: "study"
      TOKEN_SERVICE_ADDRESS: "http://meddream-token-service:8088/v3/validate"
      ORTHANC_BASE_URL: "http://orthanc-for-api:8042"
      ORTHANC_USER: "meddream"
      ORTHANC_MEDDREAM_PYTHON_PLUGIN_ENABLED: "true"
      MEDDREAM_ADMIN_PASSWORD: "change-me"
      ORTHANC_PWD: "change-me"
    volumes:
      - meddream-license:/opt/meddream/license
      - meddream-settings:/opt/meddream/sys/settings

volumes:
  orthanc-db:
  keycloak-db:
  meddream-license:
  meddream-settings:

secrets:
  SECRET_KEY:
    file: secrets/SECRET_KEY
 
