## THIS IS LICENCED UNDER TECHXPLOIT.COM.NG.................
## ANY MODIFICATION TO THIS FILE REQUIRES APPROVAL.........

## THIS CONFIGURATION IS FOR THE ON GROUND SERVER AT FMC........
## REFER TO CLOUD FOR CLOUD COMPOSE FILES................

version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx:23.12.2
    depends_on: [orthanc, orthanc-auth-service, orthanc-for-api, meddream-viewer, keycloak]
    restart: unless-stopped
    ports: ["8000:80"]
# if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
#    ports: ["443:443"]
#    volumes:
#      - /.../crt.pem:/etc/nginx/tls/crt.pem
#      - /.../key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_OHIF: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "true"
      ENABLE_HTTPS: "false"
      ENABLE_MEDDREAM: "true"
      ENABLE_ORTHANC_FOR_API: "true"

  orthanc:
    image: osimis/orthanc:master-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
    depends_on: [orthanc-db]
    ports: ["4242:4242"]
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      VOLVIEW_PLUGIN_ENABLED: "false"
      OSIMIS_WEB_VIEWER_PLUGIN_ENABLED: "false"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: '["PatientBirthDate"]'
      ORTHANC_JSON: |
        {
          "Name": "FMCA CLOUD PACS",
          "StorageCompression" : true,
          "MaximumStorageSize" : 0,
          "MaximumPatientCount" : 0,
          "MaximumStorageCacheSize" : 128,
          "MaximumStorageMode" : "Recycle",
          "LuaHeartBeatPeriod" : 0,
          "LuaScripts" : [
          ],
          "ConcurrentJobs" : 10,
          "JobsEngineThreadsCount" : {
            "ResourceModification": 1
          },
          "WebDavEnabled" : true,
          "WebDavDeleteAllowed" : false,
          "WebDavUploadAllowed" : true,
          "DicomServerEnabled" : true,
          "DicomAet" : "SERVERMAIN",
          "DicomCheckCalledAet" : true,
          "DicomPort" : 4242,
          "DefaultEncoding" : "Latin1",
          "AcceptedTransferSyntaxes" : [ "1.2.840.10008.1.*" ],
          "UnknownSopClassAccepted" : false,
          "DicomScpTimeout" : 30,
          "SslEnabled" : false,
          "SslCertificate" : "certificate.pem",
          "SslMinimumProtocolVersion" : 4,
          "SslVerifyPeers" : false,
          "SslTrustedClientCertificates" : "trustedClientCertificates.pem",
          "DicomTlsEnabled" : false,
          "DicomTlsRemoteCertificateRequired" : true,
          "DicomAlwaysAllowEcho" : true,
          "DicomAlwaysAllowStore" : true,
          "DicomAlwaysAllowFind" : true,
          "DicomAlwaysAllowFindWorklist" : true,
          "DicomAlwaysAllowGet" : true,
          "DicomAlwaysAllowMove" : true,
          "DicomCheckModalityHost" : false,
          "DicomModalities" : {
            "dentalxtray" : [ "DENTALMAIN", "192.168.43.9", 104],
            "microdicom" : [ "MICRODICOM", "192.168.43.8", 11112],
            "radiant" : [ "RADIANT", "192.168.43.8", 11113]
          },
          "DicomModalitiesInDatabase" : false,
          "DicomEchoChecksFind" : true,
          "DicomScuTimeout" : 10,
          "DicomScuPreferredTransferSyntax" : "1.2.840.10008.1.2.1",
          "DicomThreadsCount" : 4,
          "OrthancPeers" : {
          },
          "OrthancPeersInDatabase" : false,
          "HttpProxy" : "",
          "HttpVerbose" : false,
          "HttpTimeout" : 60,
          "HttpsVerifyPeers" : true,
          "HttpsCACertificates" : "/etc/ssl/certs/ca-certificates.crt",
          "UserMetadata" : {
            // "Sample" : 1024
          },
          "UserContentType" : {
            // "sample" : 1024
            // "sample2" : [ 1025, "application/pdf" ]
          },
          "StableAge" : 60,
          "StrictAetComparison" : false,
          "StoreMD5ForAttachments" : true,
          "LimitFindResults" : 0,
          "LimitFindInstances" : 0,
          "LogExportedResources" : false,
          "KeepAlive" : true,
          "TcpNoDelay" : true,
          "HttpThreadsCount" : 50,
          "StoreDicom" : true,
          "DicomAssociationCloseDelay" : 5,
          "QueryRetrieveSize" : 100,
          "CaseSensitivePN" : false,
          "LoadPrivateDictionary" : true,
          "Dictionary" : {
          },
          "SynchronousCMove" : true,
          "JobsHistorySize" : 10,
          "SaveJobs" : true,
          "OverwriteInstances" : false,
          "MediaArchiveSize" : 1,
          "StorageAccessOnFind" : "Always",
          "MetricsEnabled" : true,
          "ExecuteLuaEnabled" : false,
          "HttpRequestTimeout" : 30,
          "DefaultPrivateCreator" : "",
          "StorageCommitmentReportsSize" : 100,
          "TranscodeDicomProtocol" : true,
          "BuiltinDecoderTranscoderOrder" : "After",
          "IngestTranscoding" : "1.2.840.10008.1.2.4.91",
          "IngestTranscodingOfUncompressed" : true,
          "IngestTranscodingOfCompressed" : true,
          "DicomLossyTranscodingQuality" : 90,
          "SyncStorageArea" : true,
          "MallocArenaMax" : 5,
          "DeidentifyLogs" : true,
          "DeidentifyLogsDicomVersion" : "2021b",
          "MaximumPduLength" : 16384,
          "CheckRevisions" : false,
          "SynchronousZipStream" : true,
          "ZipLoaderThreads": 0,
          "Warnings" : {
            "W001_TagsBeingReadFromStorage": true,
            "W002_InconsistentDicomTagsInDb": true
          },
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "UiOptions": {
              "EnableOpenInMedDreamViewer": true,
              "EnableOpenInOhifViewer3": true,
              "EnableShares": true,
              "DefaultShareDuration": 0,
              "ShareDurations": [0, 7, 15, 30, 90, 365]
            },
            "Tokens" : {
              "InstantLinksValidity": 3600,
              "ShareType": "meddream-viewer-publication"
            },
            "Keycloak" : {
              "Enable": true,
              "Url": "http://localhost/keycloak/",
              "Realm": "orthanc",
              "ClientId": "orthanc"
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "change-me",
            "StandardConfigurations" : [
              "osimis-web-viewer",
              "stone-webviewer",
              "orthanc-explorer-2"
            ],
            "CheckedLevel": "studies"
          },
          "DicomWeb": {
            "Enable": true,
            "PublicRoot": "/orthanc/dicom-web/"
          }
        }
        
        

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:23.12.2
    depends_on: [keycloak, meddream-token-service]
    # permissions can be customized in the permissions.json file
    volumes:
      - ./permissions.jsonc:/orthanc_auth_service/permissions.json
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "http://localhost/orthanc/"
      PUBLIC_LANDING_ROOT: "http://localhost/orthanc/ui/app/token-landing.html"
      USERS: |
        {
          "share-user": "change-me"
        }
      MEDDREAM_TOKEN_SERVICE_URL: "http://meddream-token-service:8088/v3/generate"
      PUBLIC_MEDDREAM_ROOT: "http://localhost/meddream/"
      PUBLIC_OHIF_ROOT: "http://localhost/ohif/"
      
  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  keycloak:
    image: orthancteam/orthanc-keycloak:23.12.2
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "change-me"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "http://localhost/keycloak"
      KC_HOSTNAME_ADMIN_URL: "http://localhost/keycloak"

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

  meddream-token-service:
    image: orthancteam/meddream-token-service:23.12.2
    restart: unless-stopped
    
  ohif:
    image: orthancteam/ohif-v3:23.12.2
#  uncomment if you want to customize ohif configuration
#    volumes:
#      - ./ohif-app-config.js:/usr/share/nginx/html/app-config.js
    restart: unless-stopped

  meddream-viewer:
    image: orthancteam/meddream-viewer:23.12.2
    restart: unless-stopped
    depends_on:
      - orthanc-for-api
    environment:
      integration: "study"
      TOKEN_SERVICE_ADDRESS: "http://meddream-token-service:8088/v3/validate"
      ORTHANC_BASE_URL: "http://orthanc-for-api:8042"
      ORTHANC_USER: "meddream-user"
      ORTHANC_PWD: "change-me"
      ORTHANC_MEDDREAM_PYTHON_PLUGIN_ENABLED: "true"
      MEDDREAM_ADMIN_PASSWORD: "change-me"
    volumes:
      - meddream-license:/opt/meddream/license

  # An orthanc dedicated for API accesses and also used by MedDream
  orthanc-for-api:
    image: osimis/orthanc:master-full
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./meddream-plugin.py:/scripts/meddream-plugin.py
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for API"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/scripts/meddream-plugin.py"
      ORTHANC__AUTHENTICATION_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-api/dicom-web/"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC_JSON: |
        {
          "RegisteredUsers": {
            "meddream-user": "change-me",
            "script-user": "change-me",
            "dicom-web-client-user": "change-me"
          }
        }


volumes:
  orthanc-storage:
  orthanc-db:
  keycloak-db:
  meddream-license: