version: "3"
services:

  nginx:
    platform: linux/amd64
    image: orthancteam/orthanc-nginx:23.11.0
    depends_on: [orthanc, orthanc-auth-service]
    restart: unless-stopped
    ports: ["8080:80"]
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_OHIF: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "true"

  orthanc:
    platform: linux/amd64
    image: osimis/orthanc:23.11.0
    volumes:
      - /data:/var/lib/orthanc/db
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC_JSON: |
        {
          "Name": "FMC MAIN SERVER 1",
          "StorageCompression" : true,
          "MaximumStorageSize" : 0,
          "ConcurrentJobs" : 10,
          "JobsEngineThreadsCount" : {
            "ResourceModification": 1
          },
          "MaximumPatientCount" : 0,
          "MaximumStorageCacheSize" : 128,
          "MaximumStorageMode" : "Recycle",
          "LuaHeartBeatPeriod" : 0,
          "LuaScripts" : [
          ],
          "WebDavDeleteAllowed" : false,
          "WebDavUploadAllowed" : true,
          "DicomServerEnabled" : true,
          "DicomAet" : "FMCAM1",
          "DicomCheckCalledAet" : true,
          "DicomPort" : 4242,
          "DefaultEncoding" : "Latin1",
          "AcceptedTransferSyntaxes" : [ "1.2.840.10008.1.*" ],
          "UnknownSopClassAccepted" : false,
          "DicomScpTimeout" : 30,
          "DicomTlsEnabled" : false,
          "DicomTlsRemoteCertificateRequired" : true,
          "DicomAlwaysAllowEcho" : true,
          "DicomAlwaysAllowStore" : true,
          "DicomAlwaysAllowFind" : true,
          "DicomAlwaysAllowFindWorklist" : true,
          "DicomAlwaysAllowGet" : true,
          "DicomAlwaysAllowMove" : true,
          "DicomCheckModalityHost" : false,
          "DicomModalities" : {
               "MICRODICOM" : [ "MICRODICOM", "192.168.43.153", 11112],
               "RADIANT" : [ "RADIANT", "192.168.43.153", 11113]
          },
          "DicomModalitiesInDatabase" : false,
          "DicomEchoChecksFind" : false,
          "DicomScuTimeout" : 10,
          "DicomScuPreferredTransferSyntax" : "1.2.840.10008.1.2.1",
          "DicomThreadsCount" : 4,
          "OrthancPeers" : {
               "CLINICIANS_SERVER"  : [ "http://192.168.77.144:8043/", "orthanc", "orthanc" ]
          },
          "OrthancPeersInDatabase" : false,
          "UserMetadata" : {
            // "Sample" : 1024
          },
          "UserContentType" : {
            // "sample" : 1024
            // "sample2" : [ 1025, "application/pdf" ]
          },
          "StableAge" : 60,
          "StrictAetComparison" : false,
          "StoreMD5ForAttachments" : true,
          "LimitFindResults" : 0,
          "LimitFindInstances" : 0,
          "LogExportedResources" : false,
          "KeepAlive" : true,
          "TcpNoDelay" : true,
          "HttpThreadsCount" : 50,
          "StoreDicom" : true,
          "DicomAssociationCloseDelay" : 5,
          "QueryRetrieveSize" : 100,
          "CaseSensitivePN" : false,
          "LoadPrivateDictionary" : true,
          "Dictionary" : {
          },
          "SynchronousCMove" : true,
          "JobsHistorySize" : 10,
          "SaveJobs" : true,
          "OverwriteInstances" : false,
          "MediaArchiveSize" : 1,
          "StorageAccessOnFind" : "Always",
          "MetricsEnabled" : true,
          "ExecuteLuaEnabled" : false,
          "HttpRequestTimeout" : 30,
          "DefaultPrivateCreator" : "",
          "StorageCommitmentReportsSize" : 100,
          "TranscodeDicomProtocol" : true,
          "BuiltinDecoderTranscoderOrder" : "After",
          "IngestTranscoding" : "1.2.840.10008.1.2.4.70",
          "IngestTranscodingOfUncompressed" : true,
          "IngestTranscodingOfCompressed" : true,
          "DicomLossyTranscodingQuality" : 90,
          "SyncStorageArea" : true,
          "MallocArenaMax" : 5,
          "DeidentifyLogs" : true,
          "DeidentifyLogsDicomVersion" : "2021b",
          "MaximumPduLength" : 16384,
          "CheckRevisions" : false,
          "SynchronousZipStream" : true,
          "ZipLoaderThreads": 0,
          "Warnings" : {
            "W001_TagsBeingReadFromStorage": true,
            "W002_InconsistentDicomTagsInDb": true
          },
          "Transfers" : {
            "Threads" : 5,
            "BucketSize" : 20480,
            "CacheSize" : 128,
            "MaxPushTransactions" : 5,
            "MaxHttpRetries" : 0
          },
          "Tcia" : {
            "Enable" : true
          },

          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "UiOptions": {
              "EnableShares": true,
              "DefaultShareDuration": 0,
              "ShareDurations": [0, 7, 15, 30, 90, 365],
              "EnableOpenInOhifViewer3": true,
              "OhifViewer3PublicRoot": "https://techxploit.com.ng/ohif/"
            },
            "Tokens" : {
              "InstantLinksValidity": 3600,
              "ShareType": "ohif-viewer-publication"
            },
            "Keycloak" : {
              "Enable": true,
              "Url": "https://techxploit.com.ng/keycloak/",
              "Realm": "orthanc",
              "ClientId": "orthanc"
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "change-me",
            "StandardConfigurations" : [
              "osimis-web-viewer",
              "stone-webviewer",
              "orthanc-explorer-2"
            ],
            "CheckedLevel": "studies"
          },
          "DicomWeb": {
            "Enable": true,
            "Root" : "/dicom-web/",
            "EnableWado" : true,
            "WadoRoot" : "/wado",
            "Host" : "localhost",
            "StudiesMetadata" : "Full",
            "SeriesMetadata" : "Full",
            "PublicRoot": "/orthanc/dicom-web/"
          }

        }
  orthanc-auth-service:
    platform: linux/amd64
    image: orthancteam/orthanc-auth-service:23.9.0
    depends_on: [keycloak]
    restart: unless-stopped
    environment:
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "https://techxploit.com.ng/orthanc/"
      PUBLIC_LANDING_ROOT: "https://techxploit.com.ng/orthanc/ui/app/token-landing.html"
      PERMISSIONS_FILE_PATH: "/orthanc_auth_service/permissions.json"
      PUBLIC_OHIF_ROOT: "https://techxploit.com.ng/ohif/"
      USERS: |
        {
          "share-user": "change-me"
        }
    secrets:
      - SECRET_KEY
    volumes:
      - ./permissions.json:/orthanc_auth_service/permissions.json
      
  keycloak:
    platform: linux/amd64
    image: orthancteam/orthanc-keycloak:23.11.0
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "https://techxploit.com.ng/keycloak"
      KC_HOSTNAME_ADMIN_URL: "https://techxploit.com.ng/keycloak"
    env_file:
      - ./secrets/KEYCLOAK_ADMIN_PASSWORD.env

  ohif:
    platform: linux/amd64
    image: orthancteam/ohif-v3:23.11.0
#  uncomment if you want to customize ohif configuration
#    volumes:
#      - ./ohif-app-config.js:/usr/share/nginx/html/app-config.js
    restart: unless-stopped

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data:Z"] 
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  orthanc-db:
  keycloak-db:

secrets:
  SECRET_KEY:
    file: secrets/SECRET_KEY

