version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx:23.11.2
    depends_on: [orthanc, orthanc-auth-service]
    restart: unless-stopped
    ports: ["8080:80"]
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_OHIF: "true"

  orthanc:
    image: osimis/orthanc:mainline-2023.10.17
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "FMCA MAIN SERVER 3"
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_ROOT_URL: "http://orthanc-auth-service:8000/"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_USER_NAME: "share-user"
      ORTHANC__AUTHORIZATION__STANDARD_CONFIGURATIONS: '["stone-webviewer", "osimis-web-viewer", "orthanc-explorer-2"]'
      ORTHANC__AUTHORIZATION__CHECKED_LEVEL: "studies"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__ENABLE: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 10
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "https://techxploit.com.ng/ohif/"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_SHARES: "true"
      ORTHANC__ORTHANC_EXPLORER_2__TOKENS__INSTANT_LINKS_VALIDITY: 3600
      ORTHANC__ORTHANC_EXPLORER_2__TOKENS__SHARE_TYPE: "stone-viewer-publication"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__ORTHANC_EXPLORER_2__KEYCLOAK__ENABLE: "true"
      ORTHANC__ORTHANC_EXPLORER_2__KEYCLOAK__URL: "https://techxploit.com.ng/keycloak/"
      ORTHANC__ORTHANC_EXPLORER_2__KEYCLOAK__REALM: "orthanc"
      ORTHANC__ORTHANC_EXPLORER_2__KEYCLOAK__CLIENT_ID: "orthanc"
    volumes:
      - /data:/var/lib/orthanc/db

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:23.11.2
    depends_on: [keycloak]
    restart: unless-stopped
    environment:
      ENABLE_KEYCLOAK: "true"
      PUBLIC_ORTHANC_ROOT: "https://techxploit.com.ng/orthanc/"
      PUBLIC_LANDING_ROOT: "https://techxploit.com.ng/orthanc/ui/app/token-landing.html"
      PERMISSIONS_FILE_PATH: "/orthanc_auth_service/permissions.json"
    secrets:
      - SECRET_KEY
    volumes:
      - ./permissions.json:/orthanc_auth_service/permissions.json


  ohif:
    image: orthancteam/ohif-v3:23.11.2
    restart: unless-stopped

  keycloak:
    image: orthancteam/orthanc-keycloak:23.11.2
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "https://techxploit.com.ng/keycloak"
      KC_HOSTNAME_ADMIN_URL: "https://techxploit.com.ng/keycloak"
    env_file:
      - ./secrets/KEYCLOAK_ADMIN_PASSWORD.env

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data:Z"] 
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  orthanc-db:
  keycloak-db:

secrets:
  SECRET_KEY:
    file: secrets/SECRET_KEY