apiVersion: v1
kind: Service
metadata:
  name: nginxapp-service-pod
  labels:
    name: nginxapp-service-pod
    app: web-server
spec:
  type: NodePort
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    name: nginxapp-pod
    app: web-server
  ports:
  - port: 80
    targetPort: 80
    NodePort: 30002
