apiVersion: v1
kind: Service
metadata:
  name: redis-service-pod
  labels:
    name: redis-pod
    app: redis
spec:
  type: NodePort
  selector:
    name: redis-pod
    app: redis
  ports:
    - port: 6334
      targetPort: 6379
      nodePort: 30003
  
