apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels:
    name: redis-pod
    app: redis
spec:
  containers:
  - name: redisapp
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
