apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    name: keycloak
    app: keycloak
spec:
  type: ClusterIP
  selector:
    name: keycloak-orthanc-deployment
    app: orthanc
  ports:
  - port: 8080
    targetPort: 8080
    