apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-db-deployment
  labels:
    name: orthanc-db-deployment
    app: orthanc
spec:
  selector:
    matchLabels:
      name: orthanc-db-deployment
      app: orthanc
  template:
    metadata:
      labels:
        name: orthanc-db-deployment
        app: orthanc
    spec:
      containers:
      - name: orthanc-db
        image: postgres:15
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: orthanc-db
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
         
      volumes: 
        - name: orthanc-db
          persistentVolumeClaim:
            claimName: orthanc-db
          
