#  Playbook to update ubuntu on servers (listed on your host)
#  This is the list of tasks that will be handled by the playbook
#  Version 1 


- name: ( fill in a name for this play)
  hosts: (your inverntory name)
  remote_user: ( specify one if available)
  pre_tasks:
    
# The second task will update and upgrade the distribution

    - name: update and upgrade distribution
      ansible.builtin.apt: 
        update_cache: true
        upgrade: dist

# install apache2 and other relevant applications

    - name: install relevant applications and package manager
      ansible.builtin.apt:
        name: 
          - apache2
          - wget
          - curl
          - unzip
          - plocate
          - git
          - aptitude
          - net-tools
        state: latest

# check if a reboot is required 
    - name: Check if a reboot is required
      ansible_builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

# Reboot if required 
    - name: Reboot
      ansible_builtin.apt:
      when: reboot_required_file.stat.exists == true